### ISSUE TITLE
Error: Cannot find module 'js-chain-libs/js_chain_libs'

### ISSUE THREAD

**Issue by atomlab** [Emurgo/tangata-manu#157]
```
/opt/# git clone --single-branch --branch master-shelley https://github.com/Emurgo/tangata-manu
/opt/# cd tangata-manu
/opt/tangata-manu # git submodule update --init --recursive js-chain-libs
Submodule 'js-chain-libs' (https://github.com/Emurgo/js-chain-libs.git) registered for path 'js-chain-libs'
Cloning into '/opt/tangata-manu/js-chain-libs'...
Submodule path 'js-chain-libs': checked out '5d2abf52c6181dbe0a45f476f3bd01e511ee22f2'
Submodule 'chain-libs' (https://github.com/Emurgo/chain-libs.git) registered for path 'js-chain-libs/chain-libs'
Cloning into '/opt/tangata-manu/js-chain-libs/chain-libs'...
Submodule path 'js-chain-libs/chain-libs': checked out '65c949441ebfda7f343123df13d2a0220237f25a'
/opt/tangata-manu #
```

git commit 

```
commit b6cc6d746e37b1b542c7cc57f3964825845599d6 (HEAD -> master-shelley, origin/master-shelley)
Merge: 5187c79 5f3f3b8
Author: Ruslan Dudin <vantuz-subhuman@yandex.ru>
Date:   Mon Feb 17 16:09:56 2020 +0300

    Merge pull request #147 from Emurgo/feature/empty-inputs-fix

    Update all tx fields from blockchain
```

yarn install
```
/opt/tangata-manu # yarn install
yarn install v1.22.0
$ cd js-chain-libs; wasm-pack build --target=nodejs; wasm-pack pack; cd ..
/bin/sh: wasm-pack: not found
/bin/sh: wasm-pack: not found
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "inversify-restify-utils > gulp-debug@4.0.0" has unmet peer dependency "gulp@>=4".
warning " > restify-cors-middleware@1.1.1" has incorrect peer dependency "restify@2.6.x - 7.x.x".
[4/4] Building fresh packages...
Done in 9.49s.
/opt/tangata-manu #
```

yarn build
```
/opt/tangata-manu # yarn build
yarn run v1.22.0
$ babel src -d dist
Successfully compiled 80 files with Babel.
Done in 5.31s.
/opt/tangata-manu #
```

run
```
/opt/tangata-manu # node ./dist/index.js
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module 'js-chain-libs/js_chain_libs'
Require stack:
- /opt/tangata-manu/dist/blockchain/shelley/utils.js
- /opt/tangata-manu/dist/blockchain/shelley/block.js
- /opt/tangata-manu/dist/blockchain/shelley/index.js
- /opt/tangata-manu/dist/entities/raw-data-parsers/shelley-data-parser.js
- /opt/tangata-manu/dist/entities/raw-data-parsers/index.js
- /opt/tangata-manu/dist/entities/index.js
- /opt/tangata-manu/dist/ioc-config/ioc-config.js
- /opt/tangata-manu/dist/ioc-config/index.js
- /opt/tangata-manu/dist/server.js
- /opt/tangata-manu/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/opt/tangata-manu/dist/blockchain/shelley/utils.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/tangata-manu/dist/blockchain/shelley/utils.js',
    '/opt/tangata-manu/dist/blockchain/shelley/block.js',
    '/opt/tangata-manu/dist/blockchain/shelley/index.js',
    '/opt/tangata-manu/dist/entities/raw-data-parsers/shelley-data-parser.js',
    '/opt/tangata-manu/dist/entities/raw-data-parsers/index.js',
    '/opt/tangata-manu/dist/entities/index.js',
    '/opt/tangata-manu/dist/ioc-config/ioc-config.js',
    '/opt/tangata-manu/dist/ioc-config/index.js',
    '/opt/tangata-manu/dist/server.js',
    '/opt/tangata-manu/dist/index.js'
  ]
}
```

tree
```
/opt/tangata-manu # tree -L 1
.
├── README.md
├── cardano-http-bridge
├── config
├── dist
├── docker
├── docs
├── flow-typed
├── jest.config.js
├── js-chain-libs
├── migrations
├── migrations-shelley
├── node_modules
├── package.json
├── scripts
├── src
├── tangata-manu-bg.png
└── yarn.lock

12 directories, 5 files
```

```
/opt/tangata-manu # tree -L 1 ./js-chain-libs/
./js-chain-libs/
├── Cargo.toml
├── LICENSE_APACHE
├── LICENSE_MIT
├── README.md
├── chain-libs
├── examples
├── jsdoc.json
├── package.json
├── pkg
├── src
├── tests
└── webpack.config.js

5 directories, 7 files
```

```
/opt/tangata-manu # tree -L 1 ./js-chain-libs/chain-libs/
./js-chain-libs/chain-libs/
├── CONTRIBUTING.md
├── Cargo.toml
├── LICENSE-APACHE
├── LICENSE-MIT
├── cardano-legacy-address
├── chain-addr
├── chain-core
├── chain-crypto
├── chain-impl-mockchain
├── chain-storage
├── chain-storage-sqlite
├── chain-storage-sqlite-old
├── chain-time
├── imhamt
├── network-core
├── network-grpc
├── sparse-array
└── typed-bytes

14 directories, 4 files
```

**Comment by SebastienGllmt** [comment]
js-chain-libs comes from https://github.com/emurgo/js-chain-libs which is also available as a package here https://www.npmjs.com/package/@emurgo/js-chain-libs-node

js-chain-libs is included in Tangata-Manu as a git submodule and you have to build it using `npm run preinstall` (compiles the Rust code to WASM). We could also just replace the submodule with the NPM package and it should work.

**Comment by atomlab** [comment]
> js-chain-libs comes from https://github.com/emurgo/js-chain-libs which is also available as a package here https://www.npmjs.com/package/@emurgo/js-chain-libs-node
> 
> js-chain-libs is included in Tangata-Manu as a git submodule and you have to build it using `npm run preinstall` (compiles the Rust code to WASM). We could also just replace the submodule with the NPM package and it should work.

That means `tangata-manu` depens on [rust](https://www.rust-lang.org/tools/install) and [wasm-pack](https://rustwasm.github.io/wasm-pack/installer/). Right? 

This [Dockerfile](https://github.com/Emurgo/tangata-manu/blob/master/docker/Dockerfile) don't correct.

**Comment by atomlab** [comment]
Okey, this  Dockerfile should  build without errors.

```
FROM ubuntu:18.04

ENV PATH /root/.cargo/bin:$PATH
ENV PATH /root/.yarn/bin:/root/.config/yarn/global/node_modules/.bin:$PATH
ENV NODE_VERSION 10.19.0
ENV YARN_VERSION 1.22.0

COPY . /opt/app

RUN apt-get update && apt-get install -y -q --no-install-recommends \
    && apt install -y build-essential curl wget \
    # Install RUST
    && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y \
    # Install wasm-pack
    && curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh  \
    # Install Nodejs
    && wget -q https://deb.nodesource.com/node_10.x/pool/main/n/nodejs/nodejs_${NODE_VERSION}-1nodesource1_amd64.deb -P /tmp \
    && apt install -y /tmp/nodejs_${NODE_VERSION}-1nodesource1_amd64.deb \
    # Install Yarn
    && curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version ${YARN_VERSION} \
    # Clean
    && apt clean \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp/* 

WORKDIR /opt/app 

RUN npm run preinstall && yarn install && yarn build \
    # Clean
    && rm -rf /root/.cargo  \
    && rm -rf /root/.npm \
    && rm -rf /root/.rustup

CMD ["node", "./dist/index.js"]
```
