### ISSUE TITLE
TypeError: Cannot read property 'inputs' of undefined

### ISSUE THREAD

**Issue by atomlab** [Emurgo/tangata-manu#159]
> @atomlab https://github.com/Atomicwallet/tangata-manu-stack-docker/pull/1/files this PR should work for mainnet.

Thank you a lot for PR! With `TANGATA_DEFAULT_NETWORK: mainnet` it starts receive blocks to postgres. But after few seconds have crashed. After restart crash happens again.

```
yarn run v1.22.0
$ rimraf ./dist && yarn run build && export NODE_ENV=${NODE_ENV:-develop} && babel-node ./src/index.js --max_old_space_size=4096 --inspect | bunyan
$ babel src -d dist
Successfully compiled 80 files with Babel.
Debugger listening on ws://127.0.0.1:9229/268a4a84-1a8e-4132-acf5-48515a6072f3
For help, see: https://nodejs.org/en/docs/inspector
[2020-03-11T10:28:21.109Z] DEBUG: yoroi-importer/79 on ubuntu1804.localdomain: [DB] pendingTxsTimeoutMinutes=60, Pending TTL is applied
[2020-03-11T10:28:21.114Z] DEBUG: yoroi-importer/79 on ubuntu1804.localdomain: Launched PostgresStorageProcessor storage processor.
[2020-03-11T10:28:21.319Z] DEBUG: yoroi-importer/79 on ubuntu1804.localdomain: Checking tip every 15 seconds
[2020-03-11T10:28:21.319Z] DEBUG: yoroi-importer/79 on ubuntu1804.localdomain: Max rollback blocks count 25
[2020-03-11T10:28:21.320Z] DEBUG: yoroi-importer/79 on ubuntu1804.localdomain: genesisHash = 5f20df933584822601f9e3f8c024eb5eb252fe8cefb24d1317dc3d432e940ebb
[2020-03-11T10:28:21.322Z]  INFO: yoroi-importer/79 on ubuntu1804.localdomain: Scheduler async: starting chain syncing loop
[2020-03-11T10:28:21.323Z]  INFO: yoroi-importer/79 on ubuntu1804.localdomain: checkTip: checking for new blocks...
[2020-03-11T10:28:21.344Z]  INFO: yoroi-importer/79 on ubuntu1804.localdomain: restify listening at http://[::]:8080
[2020-03-11T10:28:21.649Z] DEBUG: yoroi-importer/79 on ubuntu1804.localdomain: Last imported block 2703. Node status: local=179,19545 remote=179,19561 packedEpochs=179
[2020-03-11T10:28:21.651Z]  INFO: yoroi-importer/79 on ubuntu1804.localdomain: processEpochId: 0, 2703
[2020-03-11T10:28:24.558Z] DEBUG: yoroi-importer/79 on ubuntu1804.localdomain: Block parsed: 8a3285df616b45a72269bc4cf430b41e21c46899480543de2910ba456355e643 0 2729 2730
[2020-03-11T10:28:24.625Z] DEBUG: yoroi-importer/79 on ubuntu1804.localdomain: Block parsed: 0dffe54b8827422f7f182307c6d3afb881f53200133b63fa20bd9c86f8cdd552 0 2759 2760
[2020-03-11T10:28:24.665Z] DEBUG: yoroi-importer/79 on ubuntu1804.localdomain: Block parsed: f287140502526900760fd65ef9a313a878b1e6c76c506aaa8acdad554ddbdf1e 0 2789 2790
[2020-03-11T10:28:24.708Z] DEBUG: yoroi-importer/79 on ubuntu1804.localdomain: Block parsed: 0be3f8392ea63f7d7279b02ac73069ee5a2a079853302b5f79297f8ffc86c247 0 2819 2820
[2020-03-11T10:28:24.745Z] DEBUG: yoroi-importer/79 on ubuntu1804.localdomain: Block parsed: 658cba567e1d4398389229477d7fcf5be4b4649eb08a747eba41019be2a7031c 0 2849 2850
[2020-03-11T10:28:24.810Z] DEBUG: yoroi-importer/79 on ubuntu1804.localdomain: Block parsed: 6da0b26c19e447f4011c560eb4aae936f7d9185bb688e1feee36bf36ee4ea56a 0 2879 2880
[2020-03-11T10:28:24.839Z] DEBUG: yoroi-importer/79 on ubuntu1804.localdomain: Block parsed: ac0a066fe767f0eb77fdc419ada0305805ccb6a7ebfbbc1c4e7be9e3db9c4049 0 2909 2910
[2020-03-11T10:28:24.879Z] DEBUG: yoroi-importer/79 on ubuntu1804.localdomain: Block parsed: ebcc830c2359d8cc5df5c7acf938c19eac2df368de80ac9ab10c48c50aece468 0 2939 2940
[2020-03-11T10:28:24.909Z] DEBUG: yoroi-importer/79 on ubuntu1804.localdomain: Block parsed: 4144ca52b9fe377649bdabf89a9d84fd039fc5d279ba8695bc471bfeec4e9fa7 0 2969 2970
[2020-03-11T10:28:24.957Z] DEBUG: yoroi-importer/79 on ubuntu1804.localdomain: Block parsed: 3f35d7bf318981c5d4e194172a9f7ff5fe4e006fa5eb7eb7453cf595a69a1426 0 2999 3000
[2020-03-11T10:28:25.029Z] DEBUG: yoroi-importer/79 on ubuntu1804.localdomain: Block parsed: 5b906caf7d4ad6c12aadc0ef2ebf7b0985bf954c98ad0fe922744ca7de3da6da 0 3029 3030
[2020-03-11T10:28:25.084Z] DEBUG: yoroi-importer/79 on ubuntu1804.localdomain: Block parsed: fdf9f6f42e4059965845a66520a0d9a4b5f6ecba0282ac02560928001a21a2e0 0 3059 3060
[2020-03-11T10:28:25.123Z] DEBUG: yoroi-importer/79 on ubuntu1804.localdomain: Block parsed: 1d3a10863fecff9c9b7cff4179c08a76332cddf617be1e89eabcef1ca34e2c25 0 3089 3090
[2020-03-11T10:28:25.170Z] DEBUG: yoroi-importer/79 on ubuntu1804.localdomain: Block parsed: dd67f84a673f98ab35c03f3dd53f6bcda543cb39139ff993e2f217bde41b5786 0 3119 3120
[2020-03-11T10:28:25.223Z] DEBUG: yoroi-importer/79 on ubuntu1804.localdomain: Block parsed: ae18dbaa46a3bb501cb456c68618e0d7a27ebe12d08bc3501eaf88ed2e036cc1 0 3149 3150
[2020-03-11T10:28:25.320Z] DEBUG: yoroi-importer/79 on ubuntu1804.localdomain: Block parsed: 428e7352990045d9b8cc0fbf6f2874b0dceb89567122dcb7798dbc43a6cf1d6f 0 3179 3180
[2020-03-11T10:28:25.438Z] DEBUG: yoroi-importer/79 on ubuntu1804.localdomain: Block parsed: d5f55ec15c0198ff7cda159295bbcc4bcc7c533e613b7a02b9108f866cacd335 0 3209 3210
[2020-03-11T10:28:25.501Z] DEBUG: yoroi-importer/79 on ubuntu1804.localdomain: Block parsed: 1649069b624925fb3e5cf9526c6b48514bad88de6a876ad2b7bf139e7547a664 0 3239 3240
[2020-03-11T10:28:25.543Z] DEBUG: yoroi-importer/79 on ubuntu1804.localdomain: Block parsed: 96fd9277fb879b6701cf5d26d48e8756defc2fa427988a720ee36aa0b79efa29 0 3269 3270
[2020-03-11T10:28:25.573Z] DEBUG: yoroi-importer/79 on ubuntu1804.localdomain: Block parsed: 57e93e2f36686f8a68d80dc12c6d8d59be01e2ec3e5d12b34b20c3c3a55f36a2 0 3299 3300
[2020-03-11T10:28:26.167Z] DEBUG: yoroi-importer/79 on ubuntu1804.localdomain: collectTxsData.requiredUtxo [ 'a12a839c25a01fa5d118167db5acdbd9e38172ae8f00e5ac0a4997ef792a20070' ]
[2020-03-11T10:28:26.264Z] DEBUG: yoroi-importer/79 on ubuntu1804.localdomain: storeBlockTxs (0/3313, cf80534e520fa8f4bde1ed2f623553b8a6a9fd616d73bf9d4f7d6d1687685248, 3314)
[2020-03-11T10:28:26.268Z] DEBUG: yoroi-importer/79 on ubuntu1804.localdomain: storeBlockTxs.storeTx 6497b33b10fa2619c6efbd9f874ecd1c91badb10bf70850732aab45b90524d9e
[2020-03-11T10:28:26.436Z] ERROR: yoroi-importer/79 on ubuntu1804.localdomain:
    Scheduler.startAsync exited with an error: TypeError: Cannot read property 'inputs' of undefined
        at DBByron.storeTxImpl$ (/opt/app/src/entities/postgres-storage/database.js:393:38)
        at tryCatch (/opt/app/node_modules/regenerator-runtime/runtime.js:45:40)
        at Generator.invoke [as _invoke] (/opt/app/node_modules/regenerator-runtime/runtime.js:271:22)
        at Generator.prototype.(anonymous function) [as next] (/opt/app/node_modules/regenerator-runtime/runtime.js:97:21)
        at tryCatch (/opt/app/node_modules/regenerator-runtime/runtime.js:45:40)
        at invoke (/opt/app/node_modules/regenerator-runtime/runtime.js:135:20)
        at /opt/app/node_modules/regenerator-runtime/runtime.js:170:11
        at new Promise (<anonymous>)
        at callInvokeWithMethodAndArg (/opt/app/node_modules/regenerator-runtime/runtime.js:169:16)
        at AsyncIterator.enqueue (/opt/app/node_modules/regenerator-runtime/runtime.js:192:13)



Done in 49.60s.
```

last commit of tangata-manu
```
vagrant@ubuntu1804:/opt/project/tangata-manu$ git log -1
commit 1e10c17ccd0e6ffbf2665982df1637b3cf5256b7 (HEAD -> master-shelley, origin/master-shelley)
Merge: 3785d90 7ea9b00
Author: crchemist-ip <46026870+crchemist-ip@users.noreply.github.com>
Date:   Thu Mar 5 14:18:35 2020 +0200

    Merge pull request #152 from Emurgo/feature/genesis-block-postgresql-fix
    
    fixed postgresql issue on parsing genesis block.
```

last commit of cardano-http-bridge

```
vagrant@ubuntu1804:/opt/project/tangata-manu/cardano-http-bridge$ git log -1
commit 31ca1468d09e618b49459c4e1f09d1d2591cdc32 (HEAD)
Author: Mykola Kharechko <mykola.kharechko@infopulse.com>
Date:   Sat Aug 31 13:48:25 2019 +0300

    remove testnet network which is not available in newest Emurgo/rust-cardano
```

postgres

```
yoroi_blockchain_importer=# select * from bestblock;
 best_block_num 
----------------
           2703
(1 row)

yoroi_blockchain_importer=# select * from blocks ORDER BY "block_height" DESC LIMIT 1;
                            block_hash                            | epoch | slot | block_height 
------------------------------------------------------------------+-------+------+--------------
 5df29c73e17b7819d0f34fdaf7947565053cf3bb2e2e8f1b7abb87c1dec167c2 |     0 | 2702 |         2703
(1 row)

yoroi_blockchain_importer=# 
```

_Originally posted by @atomlab in https://github.com/Emurgo/tangata-manu/issues/154#issuecomment-597560123_

**Comment by crchemist-ip** [comment]
fixed in https://github.com/Emurgo/tangata-manu/pull/160

**Comment by atomlab** [comment]
It works!  Thank you!
