### ISSUE TITLE
Handling of chain forks

### ISSUE THREAD

**Issue by refi93** [Emurgo/tangata-manu#163]
We are running forks of tangata-manu (https://github.com/vacuumlabs/adalite-importer) and cardano-http-bridge (https://github.com/vacuumlabs/cardano-http-bridge) (basically the same as your repos, just with some docker scripts on top) and we faced the following issue:

cardano-http-bridge seems to have detected a fork at some point:

```
INFO 2020-04-09T17:22:40Z: protocol::ntt: HANDSHAKE OK
INFO 2020-04-09T17:22:41Z: protocol::protocol: creating initial light connection 1024
INFO 2020-04-09T17:22:41Z: protocol::protocol: subscribing on light connection 1024
INFO 2020-04-09T17:23:33Z: protocol::protocol: new async light connection 67315 from node 53094fe718b43a0767
INFO 2020-04-09T17:23:34Z: protocol::protocol: received 1 asynchronous headers
INFO 2020-04-09T17:23:34Z: exe_common::sync: Network TIP is       : 9a7e65978d2b3ba1f8ebe821f625d1dc9a491d3d72ebeb6c40ff4050a0dba0d1 (185.16496) <- a9907005960490ffd2579697c3ed3d997af3cd9575714dc84dc83c4f50df8b9a
INFO 2020-04-09T17:23:34Z: exe_common::sync: Fetching from        : ee8b35b3ea713f57c5000b942178cef876d17a90be44a1830f9b2f0e187b9914 (185.16492)
INFO 2020-04-09T17:23:34Z: exe_common::sync: First unstable epoch : 185
WARN 2020-04-09T17:23:34Z: exe_common::sync: Detected fork: local tip is no longer part of the chain: BlockRef { hash: HeaderHash(Blake2b256(0xee8b35b3ea713f57c5000b942178cef876d17a90be44a1830f9b2f0e187b9914)), date: Normal(EpochSlotId { epoch: 185, slotid: 16492 }), parent: HeaderHash(Blake2b256(0xe31dce51cfc5bdb580723bcc2cb63f964a834331481cecc99bceb5b3b589ee26)) }
ERROR 2020-04-09T17:23:43Z: cardano_http_bridge::handlers::status: error while reading difficulty from HEAD: BlockNotFound([238, 139, 53, 179, 234, 113, 63, 87, 197, 0, 11, 148, 33, 120, 206, 248, 118, 209, 122, 144, 190, 68, 161, 131, 15, 155, 47, 14, 24, 123, 153, 20])
INFO 2020-04-09T17:26:20Z: protocol::protocol: new async light connection 67317 from node 5342b99e2fdd8653de
INFO 2020-04-09T17:27:35Z: protocol::protocol: new async light connection 67318 from node 53c4642afb31aa9635
INFO 2020-04-09T17:27:35Z: protocol::protocol: received 1 asynchronous headers
INFO 2020-04-09T17:27:35Z: exe_common::sync: Network TIP is       : 64a5cf5dd32cb748389975c19907b735a6321f12cc7b751e3a0c7149af0f22b0 (185.16508) <- 13415357b96bc045798bb9ea9350f1bd489ca229dc7ea85f046b106a58fe05f4
```

and subsequently tangata-manu crashed with:

```
[2020-04-09T17:23:39.828Z] ERROR: yoroi-importer/124 on f89729f31533:
    Scheduler.startAsync exited with an error: { Error: Request failed with status code 500
        at createError (/home/docker/adalite-importer/node_modules/axios/lib/core/createError.js:16:15)
        at settle (/home/docker/adalite-importer/node_modules/axios/lib/core/settle.js:18:12)
        at IncomingMessage.handleStreamEnd (/home/docker/adalite-importer/node_modules/axios/lib/adapters/http.js:202:11)
        at IncomingMessage.emit (events.js:198:15)
        at IncomingMessage.EventEmitter.emit (domain.js:481:20)
        at endReadableNT (_stream_readable.js:1142:12)
        at processTicksAndRejections (internal/process/task_queues.js:81:17)
      config:
       { adapter: [Function: httpAdapter],
         transformRequest: { '0': [Function: transformRequest] },
         transformResponse: { '0': [Function: transformResponse] },
         timeout: 0,
         xsrfCookieName: 'XSRF-TOKEN',
         xsrfHeaderName: 'X-XSRF-TOKEN',
         maxContentLength: -1,
         validateStatus: [Function: validateStatus],
         headers:
          { Accept: 'application/json, text/plain, */*',
            'User-Agent': 'axios/0.18.1' },
         method: 'get',
         url: 'http://cardano-http-bridge:8082/mainnet/status',
         responseType: 'json',
         data: undefined },
      request:
       ClientRequest {
         _events:
          [Object: null prototype] {
            socket: [Function],
            abort: [Function],
            aborted: [Function],
            error: [Function],
            timeout: [Function],
            prefinish: [Function: requestOnPrefinish] },
         _eventsCount: 6,
         _maxListeners: undefined,
         outputData: [],
         outputSize: 0,
         writable: true,
         _last: true,
         chunkedEncoding: false,
         shouldKeepAlive: false,
         useChunkedEncodingByDefault: false,
         sendDate: false,
         _removedConnection: false,
         _removedContLen: false,
         _removedTE: false,
         _contentLength: 0,
         _hasBody: true,
         _trailer: '',
         finished: true,
         _headerSent: true,
         socket:
          Socket {
            connecting: false,
            _hadError: false,
            _parent: null,
            _host: 'cardano-http-bridge',
            _readableState: [ReadableState],
            readable: true,
            _events: [Object],
            _eventsCount: 7,
            _maxListeners: undefined,
            _writableState: [WritableState],
            writable: false,
            allowHalfOpen: false,
            _sockname: null,
            _pendingData: null,
            _pendingEncoding: '',
            server: null,
            _server: null,
            parser: null,
            _httpMessage: [Circular],
            [Symbol(asyncId)]: 11180690,
            [Symbol(kHandle)]: [TCP],
            [Symbol(lastWriteQueueSize)]: 0,
            [Symbol(timeout)]: null,
            [Symbol(kBytesRead)]: 0,
            [Symbol(kBytesWritten)]: 0 },
         connection:
          Socket {
            connecting: false,
            _hadError: false,
            _parent: null,
            _host: 'cardano-http-bridge',
            _readableState: [ReadableState],
            readable: true,
            _events: [Object],
            _eventsCount: 7,
            _maxListeners: undefined,
            _writableState: [WritableState],
            writable: false,
            allowHalfOpen: false,
            _sockname: null,
            _pendingData: null,
            _pendingEncoding: '',
            server: null,
            _server: null,
            parser: null,
            _httpMessage: [Circular],
            [Symbol(asyncId)]: 11180690,
            [Symbol(kHandle)]: [TCP],
            [Symbol(lastWriteQueueSize)]: 0,
            [Symbol(timeout)]: null,
            [Symbol(kBytesRead)]: 0,
            [Symbol(kBytesWritten)]: 0 },
         _header:
          'GET /mainnet/status HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.18.1\r\nHost: cardano-http-bridge:8082\r\nConnection: close\r\n\r\n',
         _onPendingData: [Function: noopPendingOutput],
         agent:
          Agent {
            _events: [Object],
            _eventsCount: 1,
            _maxListeners: undefined,
            defaultPort: 80,
            protocol: 'http:',
            options: [Object],
            requests: {},
            sockets: [Object],
            freeSockets: {},
            keepAliveMsecs: 1000,
            keepAlive: false,
            maxSockets: Infinity,
            maxFreeSockets: 256 },
         socketPath: undefined,
         timeout: undefined,
         method: 'GET',
         path: '/mainnet/status',
         _ended: true,
         res:
          IncomingMessage {
            _readableState: [ReadableState],
            readable: false,
            _events: [Object],
            _eventsCount: 3,
            _maxListeners: undefined,
            socket: [Socket],
            connection: [Socket],
            httpVersionMajor: 1,
            httpVersionMinor: 1,
            httpVersion: '1.1',
            complete: true,
            headers: [Object],
            rawHeaders: [Array],
            trailers: {},
            rawTrailers: [],
            aborted: false,
            upgrade: false,
            url: '',
            method: null,
            statusCode: 500,
            statusMessage: 'Internal Server Error',
            client: [Socket],
            _consuming: false,
            _dumped: false,
            req: [Circular],
            responseUrl: 'http://cardano-http-bridge:8082/mainnet/status',
            redirects: [] },
         aborted: false,
         timeoutCb: null,
         upgradeOrConnect: false,
         parser: null,
         maxHeadersCount: null,
         _redirectable:
          Writable {
            _writableState: [WritableState],
            writable: true,
            _events: [Object],
            _eventsCount: 2,
            _maxListeners: undefined,
            _options: [Object],
            _redirectCount: 0,
            _redirects: [],
            _requestBodyLength: 0,
            _requestBodyBuffers: [],
            _onNativeResponse: [Function],
            _currentRequest: [Circular],
            _currentUrl: 'http://cardano-http-bridge:8082/mainnet/status' },
         [Symbol(isCorked)]: false,
         [Symbol(outHeadersKey)]:
          [Object: null prototype] { accept: [Array], 'user-agent': [Array], host: [Array] } },
      response:
       { status: 500,
         statusText: 'Internal Server Error',
         headers:
          { 'content-length': '0', date: 'Thu, 09 Apr 2020 17:23:39 GMT' },
         config:
          { adapter: [Function: httpAdapter],
            transformRequest: [Object],
            transformResponse: [Object],
            timeout: 0,
            xsrfCookieName: 'XSRF-TOKEN',
            xsrfHeaderName: 'X-XSRF-TOKEN',
            maxContentLength: -1,
            validateStatus: [Function: validateStatus],
            headers: [Object],
            method: 'get',
            url: 'http://cardano-http-bridge:8082/mainnet/status',
            responseType: 'json',
            data: undefined },
         request:
          ClientRequest {
            _events: [Object],
            _eventsCount: 6,
            _maxListeners: undefined,
            outputData: [],
            outputSize: 0,
            writable: true,
            _last: true,
            chunkedEncoding: false,
            shouldKeepAlive: false,
            useChunkedEncodingByDefault: false,
            sendDate: false,
            _removedConnection: false,
            _removedContLen: false,
            _removedTE: false,
            _contentLength: 0,
            _hasBody: true,
            _trailer: '',
            finished: true,
            _headerSent: true,
            socket: [Socket],
            connection: [Socket],
            _header:
             'GET /mainnet/status HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.18.1\r\nHost: cardano-http-bridge:8082\r\nConnection: close\r\n\r\n',
            _onPendingData: [Function: noopPendingOutput],
            agent: [Agent],
            socketPath: undefined,
            timeout: undefined,
            method: 'GET',
            path: '/mainnet/status',
            _ended: true,
            res: [IncomingMessage],
            aborted: false,
            timeoutCb: null,
            upgradeOrConnect: false,
            parser: null,
            maxHeadersCount: null,
            _redirectable: [Writable],
            [Symbol(isCorked)]: false,
            [Symbol(outHeadersKey)]: [Object] },
         data: '' } }
[nodemon] app crashed - waiting for file changes before starting...
```

Did you face similar issues or should your tangata-manu instance already be resilient to such exceptions?

**Comment by SebastienGllmt** [comment]
Which branch are you running on? Currently our production runs on `master-shelley` (even for Byron) and not `master`. It doesn't look like either Seiza or Yoroi got stuck

**Comment by refi93** [comment]
we are running on `master`, that can explain it then, thanks!

**Comment by SebastienGllmt** [comment]
Can we close this issue if that fixed your problem?

**Comment by refi93** [comment]
yes, thanks @SebastienGllmt I managed to get the new branch running
